---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: exercise1
  labels:
    app: exercise1
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchExpressions:
      - key: activity
        operator: In
        values:
          - exercise1
          - exercise2
  template:
    metadata:
      labels:
        activity: exercise1
    spec:
      containers:
        - name: incoma
          image: alpine

